version: "3.2"

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    #image: 'rabbitmq:3.8-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    #volumes:
    #  - /opt/docker-volume/rabbitmq/lib:/var/lib/rabbitmq/
    #  - /opt/docker-volume/rabbitmq/log:/var/log/rabbitmq/
    ports:
      - '5672:5672'     # rabbitmq
      - '15672:15672'   # rabbitmq management interface